module.exports={
    xname:'Flexbox',
    props:{
        align:'start',
        direction: 'row'
    },
    children:[
        {
            presenter:'ImagePortrait',
            gateway:{
                xname:"Binding",
                props:{
                    binding:{
                        logo:'url',
                    }
                }
            }
        },
        {
            presenter:'RightContent',
            gateway:{
                xname:"Binding",
                props:{
                    binding:{
                        title:"content",
                    }
                }
            }
        }
    ]
}