module.exports={
    xname:"Flexbox",
    props:{
        align:"start",
        direction:"column",
        justidy:"center"
    },
    gateway:{
        xname:"Binding",
        props:{
            binding:{
                logo:"logo",
                title:"title",
                subtitle:"subtitle",
                timestamp:"timestamp"
            }
        }
    },
    cart:{
        xname:"ItemCart",
        props:{
            padding:'10px'
        }
    },
    container:"SelectedList"
}