module.exports={
    xname:"Flexbox",
    props:{
        align:"start",
        direction:"column",
        justidy:"center"
    },
    gateway:{
        xname:"Binding",
        props:{
            binding:{
                imgUrl:"imgUrl",
                title:"title",
                text:"text",
                time:"time"
            }
        }
    },
    cart:{
        xname:"HoverShadowCart",
        props:{
            margin:"0",
            fill:"#f0ffff"
        }
    },
    container:"PlainList"
}