module.exports={
    xname:"Flexbox",
    props:{
        align:"start",
        direction:"column",
        justidy:"center"
    },
    gateway:{
        xname:"Binding",
        props:{
            binding:{
                url:"logo",
                title:"title",
                description:"subtitle",
                update_time:"timestamp"
            }
        }
    },
    cart:{
        xname:"ItemCart",
        props:{
            padding:'10px'
        }
    },
    container:"SelectedList"
}